config/routes.rb
Rails.application.routes.draw do
  resources :categories, only: [:show]
  resources :votes, only: %i[create destroy]
  resources :articles
  resources :users, only: %i[new create]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create', as: 'login_path'
  delete 'logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'categories#index'
end

app/models/article.rb
class Article < ApplicationRecord
  mount_uploader :image, CoverUploader
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  belongs_to :category
  has_many :votes
  validates :title, presence: true,
                    length: { minimum: 5, maximum: 80, message: 'Title must be between 5 and 80 characters' }
  validates :text, presence: true
  validates :image, presence: true

  scope :newest_first, -> { order(created_at: :desc) }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]
  before_action :authorize, except: %i[index show]

  def index
    @articles = Article.all.newest_first.includes(%i[author category])
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = current_user.articles.build
  end

  def edit; end

  def create
    @article = current_user.articles.build(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :text, :image, :category_id)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  # rubocop: disable Lint/Void
  def title_error
    @article.errors.full_messages_for(:title).each do |msg|
      msg
    end
  end

  def text_error
    @article.errors.full_messages_for(:text).each do |msg|
      msg
    end
  end

  def image_error
    @article.errors.full_messages_for(:image).each do |msg|
      msg
    end
  end

  def ed_links(article)
    render 'articles/editdelete', article: article if article.author == current_user
  end

  def ed_links_show(article)
    render 'articles/edlinksforshow', article: article if article.author == current_user
  end
end
# rubocop: enable Lint/Void

app/views/articles/_editdelete.html.erb
<td><%= link_to 'Edit', edit_article_path(article), class:"list-group-item border-0 list-group-item-action btn btn-light" %></td>
<td><%= link_to 'Delete', article, method: :delete, data: { confirm: 'Are you sure?' }, class:"list-group-item border-0 list-group-item-action btn btn-light" %></td>

app/views/articles/_edlinksforshow.html.erb
<div>
  <%= link_to 'Edit', edit_article_path(@article), class:"col-3 fw-bold list-group-item list-group-item-action btn btn-light border-0" %> 
</div>
<div class="mt-2">  |
</div>
<div>
  <%= link_to 'Delete', @article, method: :delete, data: { confirm: 'Are you sure?' }, class:"col-3 fw-bold list-group-item list-group-item-action btn btn-light border-0" %>
</div>
  <div class="mt-2">  |
</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  

  <div class="field my-3">
    <%= form.text_field :title, class:"form-control my-2", placeholder:"Title" %>
  </div>
  <p class="text-danger"><%= title_error.join(', ') %></p>
  <div class="field my-4">
    
    <%= form.text_area :text, class:"form-control my-2 texta", placeholder:"Text" %>
  </div>
   <p class="text-danger"><%= text_error.join(', ') %></p>
  <div class="field my-3">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>
   <p class="text-danger"><%= image_error.join(', ') %></p>
    <div class="field my-3">
    <%= form.label :category %>
    <%= form.collection_select :category_id, Category.all, :id, :name %>  
  </div>

  
     <div class="actions col-6 mx-auto my-4">
     <%= submit_tag "Save article", class:"col-3 fw-bold list-group-item text-center list-group-item-action btn btn-light" %>
    </div>
<% end %>

  
  

app/views/articles/edit.html.erb
<div class="col-5 m-auto"> 
<h1 class="text-center fs-4 fw-bold my-5">Make your changes</h1>

<%= render 'form', article: @article %>
<div class="d-flex justify-content-center gap-3 mt-4">
    <div>
        <%= link_to 'Show', @article, class:"col-3 fw-bold list-group-item list-group-item-action btn btn-light border-0" %> 
    </div>
    <div class="mt-2">  |
    </div>
    <div>
        <%= link_to 'Delete', @article, method: :delete, data: { confirm: 'Are you sure?' }, class:"col-3 fw-bold list-group-item list-group-item-action btn btn-light border-0" %>
    </div>
    <div class="mt-2">  |
    </div>
    <div>
        <%= link_to 'Back', articles_path, class:"col-3 fw-bold list-group-item list-group-item-action btn btn-light border-0" %>

    </div>
  </div>
</div>
<div class="sticky">
    <%= render 'layouts/footer' %>
</div>

app/views/articles/index.html.erb
<div class= "wrapper mx-5">
  <h1 class="text-center fs-4 fw-bold my-5">All articles</h1>

  <table class="table">
    <thead>
      <tr>
        <th scope="col">Title</th>
        <th scope="col">Author</th> 
        <th scope="col">Category</th>
        <th scope="col">Created</th>      
      </tr>
    </thead>
    <tbody>
      <% @articles.each do |article| %>
        <tr>
        <td><%= link_to article.title, article, class:"list-group-item border-0 list-group-item-action btn btn-light text-decoration-underline" %></td>
        <td><%= article.author.name %></td>
        <td><%= article.category.name %></td> 
        <td><%= article.created_at %></td> 
        <td ><%= button_to 'Vote', controller: :votes, action: :create, method: :post, :article_id => article.id, class:"btn btn-light" %>
          
        <%= ed_links(article)%>
      <% end %>
      </tr>    
    </tbody>
  </table>
</div>
<div class="sticky">
  <%= render 'layouts/footer' %>
</div>

app/views/articles/new.html.erb
<div class="col-5 m-auto"> 
 
  <h1 class="text-center fs-4 fw-bold my-4">Create new article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path,class:"col-3 fw-bold list-group-item list-group-item-action btn btn-light border-0" %>
</div>
  

app/views/articles/show.html.erb
<div class="col-5 m-auto"> 
<h1 class="text-center fs-3 fw-bold mt-5"><%= @article.title %></h1>
<p class="fw-bold text-center mt-4">Author: <%= @article.author.name %>  | Category: <%= @article.category.name %> </p>
  <div class=" mx-auto col-8">
    
    <img src="<%= @article.image %>" class="my-4 article-img img-fluid" >
  </div>

  <p class="">
    <%= @article.text %>
  </p>

  <p class="fw-bold mt-4">Exists: <%= time_ago_in_words @article.created_at%>
  </p>

  <p class="fw-bold mt-4">Votes: <%= @article.votes.count%></p>

  <div class="my-4">
    <%= button_to 'Vote', controller: :votes, action: :create, method: :post, :article_id => @article.id, class:"btn btn-light" %>
  </div>
  <div class="d-flex justify-content-center gap-3 mt-4">
    <%= ed_links_show(@article) %>
    <div>
      <%= link_to 'Back', articles_path,class:"col-3 fw-bold list-group-item list-group-item-action btn btn-light border-0" %>
    </div>                
  
  </div>
</div>
<div class="sticky">
    <%= render 'layouts/footer' %>
</div>