config/routes.rb
Rails.application.routes.draw do
  resources :categories, only: [:show]
  resources :votes, only: %i[create destroy]
  resources :articles
  resources :users, only: %i[new create]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create', as: 'login_path'
  delete 'logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'categories#index'
end

app/views/layouts/_alerts.html.erb
<div class="alert alert-danger alert-dismissible fade show" role="alert">
  <%= alert %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/_footer.html.erb
<footer class="mb-0 pb-4 bgbrown container-fluid d-flex justify-content-between">
<div>
    <%= link_to root_path, class:"navbar-brand link" do %>
        <% image_tag "logo.svg", class:"mt-2 logo ms-3"%>
        <%end%>
    </div>

<div class="mt-2">
        <ul class="list-group list-group-horizontal mt-3">
                <li class="nav-item">
                <a class="list-group-item bgbrown list-group-item-action  torange fw-bold border-0" aria-current="page" href="https://en.wikipedia.org/wiki/Privacy_policy">Privacy policy</a>
                </li>
                <li class="nav-item">
                <a class="list-group-item bgbrown list-group-item-action  torange fw-bold border-0" aria-current="page" href="https://en.wikipedia.org/wiki/Terms_of_service">Terms & Conditions</a>
                </li>
                <li class="nav-item">
                <p class="list-group-item bgbrown list-group-item-action text-light  fw-bold border-0">Made by 1v4n4  © 2021 </p>
                </li>                
        </ul>
    </div>

    <div>
        <ul class="list-group list-group-horizontal mt-3">
                <li class="nav-item">
                <a href="https://github.com/1v4n4" class="list-group-item bgbrown list-group-item-action  torange fw-bold border-0" target="_blank" aria-current="page" href="#"><i class="fa fa-github fa-2x"></i></a>
                </li>
                <li class="nav-item">
                <a class="list-group-item bgbrown list-group-item-action  torange fw-bold border-0" aria-current="page" target="_blank" href="https://twitter.com/codeIv1"><i class="fa fa-twitter fa-2x"></i></a>
                </li>
                <li class="nav-item">
                <a class="list-group-item bgbrown list-group-item-action torange  fw-bold border-0" aria-current="page" target="_blank" href="https://www.linkedin.com/in/1v4n4"><i class="fa fa-linkedin fa-2x"></i> </a>
                </li>                
        </ul>
        
    </div>


</footer>

app/views/layouts/_h1.html.erb
<div class="d-flex align-items-center pt-4">
  <p class="nav-item fw-bold pt-2">Logged in as: 
    <%= current_user.name %>
  </p>
  <p class="nav-item pt-1 mx-3">
    <%= link_to 'Create new article', new_article_path, class:"fw-bold list-group-item border-0 list-group-item-action btn btn-light" %>
  </p>
  <p class="nav-item">
    <%= button_to 'Log out', logout_path, method: :delete, controller: :sessions, action: :destroy, class:"fw-bold list-group-item list-group-item-action btn btn-light" %>
  </p>
</div>

app/views/layouts/_h2.html.erb
<ul class="list-group list-group-horizontal">
                    <li class="nav-item pt-2 mt-4">
                        <%= link_to "Log in", login_path, class:"fw-bold list-group-item border-0 list-group-item-action btn btn-light" %>
                    </li>
                    <li class="nav-item"><p class="fs-4 pt-3 mt-4 me-1"> | </p></li>
                    <li class="nav-item pt-2 mt-4">
                    <%= link_to "Sign up", new_user_path, class:"fw-bold list-group-item border-0 list-group-item-action btn btn-light" %>
                    </li>
                </ul>

app/views/layouts/_header.html.erb
<nav class="header container-fluid d-flex justify-content-between">

    <div>
        <%= link_to root_path, class:"navbar-brand link" do %>
        <%= image_tag "logo.svg", class:"logo ms-5"%><p class="logo-txt ms-1 text-dark fw-bold fst-italic text-center">Do - magazine with <br> great music taste</p>
        <%end%>
    </div>
    <div>
        <ul class="list-group list-group-horizontal mt-4 pt-2">
                <li class="nav-item">
                    <%= link_to "Cover story", category_path(1), class:"list-group-item  list-group-item-action torange fs-5 fw-bold border-0"%>
                </li>
                <li class="nav-item">
                    <%= link_to "News", category_path(2), class:"list-group-item list-group-item-action fs-5 fw-bold border-0"%>
                </li>
                <li class="nav-item">
                	<%= link_to "Interviews", category_path(3), class:"list-group-item list-group-item-action fs-5 fw-bold border-0"%>
                </li>
                <li class="nav-item">
                  <%= link_to "Live", category_path(4), class:"list-group-item list-group-item-action fs-5 fw-bold border-0"%>
                </li>
                <li class="nav-item">
                	<%= link_to "Reviews", category_path(5), class:"list-group-item list-group-item-action fs-5 fw-bold border-0"%>
                </li>
                <li class="nav-item">
                	<%= link_to "All articles", articles_path, class:"list-group-item list-group-item-action fs-5 fw-bold border-0"%>
                </li>
        </ul>
    </div>
    <div>

        <%= render log %>



    </div>

</nav>

app/views/layouts/_notices.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta property="og:image" content="https://user-images.githubusercontent.com/65791349/123562058-8c1d2880-d7ac-11eb-883e-4f0228e46630.png">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <title>Do</title>
  </head>

  <body>
  <div class="border">
  <%= render 'layouts/header'%> 
  <div class="yield">
  <div class="alerts fixed1">   
      <%= alertss(alert) %>
      <%= noticess(notice) %>
    </div>
   <div class="yi">
    <%= yield %>
    </div>
  </body>
</html>